name: Analyze and Test 

on:
  pull_request:

jobs:
  lint:
    name: Alayze the code
    runs-on: ubuntu-latest
    steps:
      - name: Clone flutter repository from stable channel with 3.3.10 version
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.10'
          channel: 'stable'

      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Update dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze
  
  test:
    name: Test with coverage on ubuntu-latest
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone flutter repository from stable channel with 3.3.10 version
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.10'
          channel: 'stable'

      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Update dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Test and get test coverage
        run: flutter test --coverage

      - name: Very good ventuers test coverage
        uses: VGVentures/very-good-coverage@v1.1.1
        with:
          path: "./coverage/lcov.info"
          min_coverage: 10

      - name: Upload to coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info